name: Build Unreal Engine plugin

on:
  push:
      branches:
        - main

jobs:
  build-and-package:
    runs-on:
      group: unreal-engine-public-plugins

    services:
      unreal-engine:
        image: ghcr.io/epicgames/unreal-engine:dev-slim-5.4.2

        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

    steps:
      - name: Checkout repo
        uses: actions/Checkout@v4

      - name: Extract repository name
        run: echo "PLUGIN_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

        - name: List directories
            run: |
              ls
              cd /home/ue4
              ls

      - name: Build and Package Plugin
        run: |
          cd /home/ue4/UnrealEngine
          ./Engine/Build/BatchFiles/RunUAT.sh BuildPlugin -plugin=${{ github.workspace }}/${{ env.PLUGIN_NAME }}.uplugin -package=${{ github.workspace }}/output -targetplatforms=Linux -utf8output -rocket

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packaged-plugin_${{ github.sha }}
          path: ${{ github.workspace }}/output
    
