name: Build Unreal Engine plugin

on:
  push:
      branches:
        - main

jobs:
  build-and-package:
    runs-on:
      group: unreal-engine-public-plugins

    steps:
      - name: Checkout repo
        uses: actions/Checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract repository name
        run: echo "PLUGIN_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Build and Package Plugin
        run: |
          docker run --rm -i -v "${{ github.workspace }}:/project" -w /home/ue4/UnrealEngine ghcr.io/epicgames/unreal-engine:dev-slim-5.4.2 \
          ./Engine/Build/BatchFiles/RunUAT.sh \
          BuildPlugin \
          -plugin=/project/${{ env.PLUGIN_NAME }}.uplugin \
          -package=/project/output \
          -targetplatforms=Linux \
          -utf8output \
          -rocket

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packaged-plugin_${{ github.sha }}
          path: ${{ github.workspace }}/output
    
